import { describe, it, expect } from "vitest";
import { assemble } from "../src/assemble.js";
import type { Block } from "../src/blocks.js";

describe("assemble", () => {
  it("produces one self-contained HTML doc with inlined CSS, header, and rendered blocks", async () => {
    const blocks: Block[] = [
      { type: "prose", id: "p", markdown: "Intro **text**." },
      { type: "diagram", id: "flow", title: "Flow", kind: "flowchart", d2: "a -> b" },
    ];
    const html = await assemble(blocks, {
      title: "Test Plan", source: "spec.md", status: { level: "green", text: "ready" },
    });
    expect(html).toMatch(/^<!doctype html>/i);
    expect(html).toContain("<style>");
    expect(html).not.toContain("<link");
    expect(html).toContain("Test Plan");
    expect(html).toContain("spec.md");
    expect(html).toContain('class="vs-status green"');
    expect(html).toContain("<strong>text</strong>");
    expect(html).toContain("<svg");
    expect(html).not.toContain("<script");
  });

  it("renders annotated-code and questions blocks without throwing", async () => {
    const blocks: Block[] = [
      {
        type: "annotated-code", id: "ac", title: "flow", lang: "ts",
        code: "const a = 1;\nconst b = 2;",
        annotations: [{ line: 1, note: "first" }],
      },
      {
        type: "questions", id: "q", title: "Open questions",
        questions: [{ question: "Ship it?", recommendedDefault: "yes" }],
      },
    ];
    const html = await assemble(blocks, { title: "All Blocks", source: "spec.md" });
    expect(html).toContain('class="vs-block vs-annotated"');
    expect(html).toContain('class="vs-block vs-questions"');
    expect(html).toContain("first");
    expect(html).toContain("Ship it?");
    expect(html).not.toContain("<script");
  });

  it("renders a generator stamp in a footer and meta tag when provided", async () => {
    const html = await assemble([{ type: "prose", id: "p", markdown: "hi" }], {
      title: "T", source: "s", generator: "visual-skills@abc123 · 2026-06-17T23:10:00Z",
    });
    expect(html).toContain('<meta name="generator" content="visual-skills@abc123 · 2026-06-17T23:10:00Z">');
    expect(html).toContain('class="vs-generator"');
    expect(html).toContain("Generated by visual-skills@abc123");
  });

  it("omits the generator footer/meta when not provided", async () => {
    const html = await assemble([{ type: "prose", id: "p", markdown: "hi" }], { title: "T", source: "s" });
    expect(html).not.toContain('name="generator"');
    // The .vs-generator CSS rule is always inlined; assert the footer ELEMENT is absent.
    expect(html).not.toContain('<footer class="vs-generator"');
  });
});
