import { describe, it, expect } from "vitest";
import { assemble } from "../src/assemble.js";
import type { Block } from "../src/blocks.js";

describe("assemble", () => {
  it("produces one self-contained HTML doc with inlined CSS, header, and rendered blocks", async () => {
    const blocks: Block[] = [
      { type: "prose", id: "p", markdown: "Intro **text**." },
      { type: "diagram", id: "flow", title: "Flow", kind: "flowchart", d2: "a -> b" },
    ];
    const html = await assemble(blocks, {
      title: "Test Plan", source: "spec.md", status: { level: "green", text: "ready" },
    });
    expect(html).toMatch(/^<!doctype html>/i);
    expect(html).toContain("<style>");
    expect(html).not.toContain("<link");
    expect(html).toContain("Test Plan");
    expect(html).toContain("spec.md");
    expect(html).toContain('class="vs-status green"');
    expect(html).toContain("<strong>text</strong>");
    expect(html).toContain("<svg");
    expect(html).not.toContain("<script");
  });

  it("renders annotated-code and questions blocks without throwing", async () => {
    const blocks: Block[] = [
      {
        type: "annotated-code", id: "ac", title: "flow", lang: "ts",
        code: "const a = 1;\nconst b = 2;",
        annotations: [{ line: 1, note: "first" }],
      },
      {
        type: "questions", id: "q", title: "Open questions",
        questions: [{ question: "Ship it?", recommendedDefault: "yes" }],
      },
    ];
    const html = await assemble(blocks, { title: "All Blocks", source: "spec.md" });
    expect(html).toContain('class="vs-block vs-annotated"');
    expect(html).toContain('class="vs-block vs-questions"');
    expect(html).toContain("first");
    expect(html).toContain("Ship it?");
    expect(html).not.toContain("<script");
  });

  it("renders a generator stamp in a footer and meta tag when provided", async () => {
    const html = await assemble([{ type: "prose", id: "p", markdown: "hi" }], {
      title: "T", source: "s", generator: "visual-skills@abc123 · 2026-06-17T23:10:00Z",
    });
    expect(html).toContain('<meta name="generator" content="visual-skills@abc123 · 2026-06-17T23:10:00Z">');
    expect(html).toContain('class="vs-generator"');
    expect(html).toContain("Generated by visual-skills@abc123");
  });

  it("omits the generator footer/meta when not provided", async () => {
    const html = await assemble([{ type: "prose", id: "p", markdown: "hi" }], { title: "T", source: "s" });
    expect(html).not.toContain('name="generator"');
    // The .vs-generator CSS rule is always inlined; assert the footer ELEMENT is absent.
    expect(html).not.toContain('<footer class="vs-generator"');
  });

  it("renders a group with nested blocks, anchors, and a nested diagram", async () => {
    const blocks: Block[] = [
      { type: "prose", id: "summary", title: "Summary", markdown: "hi" },
      { type: "group", id: "g1", title: "Core change", blocks: [
        { type: "diagram", id: "flow", title: "Flow", kind: "flowchart", d2: "a -> b" },
        { type: "diff", id: "diff-0", title: "x.ts", path: "src/x.ts", hunks: [{ header: "@@", lines: ["+a"] }] },
      ] },
    ];
    const html = await assemble(blocks, { title: "T", source: "s" });
    expect(html).toContain('class="vs-block vs-group"');
    expect(html).toContain("Core change");
    expect(html).toContain('id="g1"');     // group anchor
    expect(html).toContain('id="flow"');   // nested diagram anchor
    expect(html).toContain('id="diff-0"'); // nested diff anchor
    expect(html).toContain("<svg");        // nested diagram actually rendered
    expect(html).not.toContain("<script");
  }, 30_000);

  it("stamps an id anchor on a top-level block section", async () => {
    const html = await assemble([{ type: "prose", id: "p1", markdown: "x" }], { title: "T", source: "s" });
    expect(html).toContain('id="p1"');
  });

  it("throws on a nested group (groups may not nest)", async () => {
    const blocks: Block[] = [
      { type: "group", id: "g1", title: "A", blocks: [{ type: "group", id: "g2", title: "B", blocks: [] }] },
    ];
    await expect(assemble(blocks, { title: "T", source: "s" })).rejects.toThrow(/nest/);
  });

  it("throws on duplicate block ids (anchors/cross-links must be unique)", async () => {
    const blocks: Block[] = [
      { type: "prose", id: "dup", markdown: "a" },
      { type: "prose", id: "dup", markdown: "b" },
    ];
    await expect(assemble(blocks, { title: "T", source: "s" })).rejects.toThrow(/duplicate block id/);
  });

  it("throws on a duplicate id nested in a group", async () => {
    const blocks: Block[] = [
      { type: "prose", id: "x", markdown: "a" },
      { type: "group", id: "g", title: "G", blocks: [{ type: "prose", id: "x", markdown: "b" }] },
    ];
    await expect(assemble(blocks, { title: "T", source: "s" })).rejects.toThrow(/duplicate block id/);
  });
});
