import { readFile } from "node:fs/promises";
import { join, basename } from "node:path";
import { fileURLToPath } from "node:url";
import type { Block } from "./blocks.js";
import { isDiagramBlock } from "./blocks.js";
import { escapeHtml } from "./html.js";
import { renderAll } from "./render-diagram.js";
import { renderProse } from "./renderers/prose.js";
import { renderFileTree } from "./renderers/file-tree.js";
import { renderDiff } from "./renderers/diff.js";
import { renderApi } from "./renderers/api.js";
import { renderAnnotatedCode } from "./renderers/annotated-code.js";
import { renderQuestions } from "./renderers/questions.js";

export interface DocStatus { level: "green" | "yellow" | "red"; text: string; }
export interface AssembleOpts {
  title: string;
  source: string;
  status?: DocStatus;
  outDir?: string;
  excalidraw?: boolean;
  onWarn?: (msg: string) => void;
  generator?: string;
}

const ASSETS = fileURLToPath(new URL("../assets", import.meta.url));

export async function assemble(blocks: Block[], opts: AssembleOpts): Promise<string> {
  // Render every diagram/schema block to inline SVG up front (preserves order by id).
  const diagramBlocks = blocks.filter(isDiagramBlock);
  const rendered = await renderAll(diagramBlocks, {
    outDir: opts.outDir, excalidraw: opts.excalidraw, onWarn: opts.onWarn,
  });
  const svgById = new Map<string, (typeof rendered)[number]>();
  for (const r of rendered) {
    if (svgById.has(r.id)) {
      throw new Error(`duplicate diagram/schema block id "${r.id}" — block ids must be unique`);
    }
    svgById.set(r.id, r);
  }

  const fragments = await Promise.all(
    blocks.map(async (b) => {
      switch (b.type) {
        case "diagram":
        case "schema": {
          const r = svgById.get(b.id)!;
          const link = r.editable
            ? `<div class="vs-edit"><a href="${escapeHtml(basename(r.editable))}">open in Excalidraw</a></div>`
            : "";
          // r.svg is trusted: produced by the d2 binary (or dormant Excalidraw), which emit no <script>.
          return `<section class="vs-block vs-diagram"><h2>${escapeHtml(b.title)}</h2>${r.svg}${link}</section>`;
        }
        case "prose": return await renderProse(b, opts.onWarn);
        case "file-tree": return renderFileTree(b);
        case "diff": return await renderDiff(b, opts.onWarn);
        case "api": return renderApi(b);
        case "annotated-code": return await renderAnnotatedCode(b, opts.onWarn);
        case "questions": return renderQuestions(b);
        default: {
          const _exhaustive: never = b;
          throw new Error(`unhandled block type: ${(_exhaustive as Block).type}`);
        }
      }
    }),
  );

  const css = await readFile(join(ASSETS, "template.css"), "utf8");
  const status = opts.status
    ? `<span class="vs-status ${opts.status.level}">${escapeHtml(opts.status.text)}</span>`
    : "";
  const header =
    `<header class="vs-header"><h1>${escapeHtml(opts.title)}</h1>` +
    `<div class="vs-source">${escapeHtml(opts.source)}</div>${status}</header>`;

  return (
    `<!doctype html>\n<html lang="en"><head><meta charset="utf-8">` +
    `<meta name="viewport" content="width=device-width, initial-scale=1">` +
    `${opts.generator ? `<meta name="generator" content="${escapeHtml(opts.generator)}">` : ""}` +
    `<title>${escapeHtml(opts.title)}</title><style>${css}</style></head>` +
    `<body><main class="vs-doc">${header}${fragments.join("")}${opts.generator ? `<footer class="vs-generator">Generated by ${escapeHtml(opts.generator)}</footer>` : ""}</main></body></html>\n`
  );
}
